const NAMESPACE = {
  AUTHENTICATION: "AUTHENTICATION",
  USER_MANAGEMENT: "USER_MANAGEMENT",
  LESSON_MANAGEMENT: "LESSON_MANAGEMENT",
  FILE_MANAGEMENT: "FILE_MANAGEMENT",
  SETTING: "SETTING",
  LOGIN: "LOGIN",
  COURSE_MANAGEMENT: "COURSE_MANAGEMENT",
};
export default NAMESPACE;
