export const stageData = [
  {
    id: "1",
    name: "Đường lối cách mạng",
    stage: 1,
    file: "Consequat.ppt",
    start_date: "2020-10-23",
    index: 1,
    status: "n",
  },
  {
    id: "5",
    name: "Hoá hữu cơ",
    stage: 2,
    file: "UtTellusNulla.avi",
    start_date: "2020-04-15",
    index: 2,
    status: "s",
  },
  {
    id: "3",
    name: "Quốc phòng 1",
    stage: 3,
    file: "ProinAt.avi",
    start_date: "2020-10-11",
    index: 3,
    status: "n",
  },
  {
    id: "4",
    name: "Tin cơ sở",
    stage: 4,
    file: "Dui.jpeg",
    start_date: "2021-03-03",
    index: 4,
    status: "f",
  },
  {
    id: "5",
    name: "Hoá hữu cơ",
    stage: 5,
    file: "TurpisEnimBlandit.gif",
    start_date: "2021-02-24",
    index: 5,
    status: "n",
  },
  {
    id: "3",
    name: "Quốc phòng 1",
    stage: 6,
    file: "FaucibusOrci.ppt",
    start_date: "2021-01-01",
    index: 6,
    status: "f",
  },
  {
    id: "4",
    name: "Tin cơ sở",
    stage: 7,
    file: "Non.mp3",
    start_date: "2020-10-09",
    index: 7,
    status: "n",
  },
];
